[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sqlittaaja"
readme = "README.md"
requires-python = ">=3.11"
dynamic = ["version"]

[project.scripts]
sqlittaaja = "sqlittaaja:main"

[tool.setuptools]

[tool.setuptools_scm]
